FROM php:8.3-cli-alpine

# Install minimal extensions
RUN apk add --no-cache sqlite-libs && \
    docker-php-ext-install pdo_sqlite

# Composer
COPY --from=composer:latest /usr/bin/composer /usr/bin/composer

WORKDIR /app

COPY composer.json composer.lock symfony.lock* ./
RUN composer install --no-interaction

COPY . .
RUN mkdir -p var && chmod -R 777 var

EXPOSE 8000

CMD ["php", "-S", "0.0.0.0:8000", "-t", "public"]
